# ── Glue Demo — Outputs ─────────────────────────────────────────────────────

output "confluent_environment_id" {
  description = "Confluent environment ID"
  value       = module.core.environment_id
}

output "confluent_cluster_id" {
  description = "Confluent Kafka cluster ID"
  value       = module.core.kafka_cluster_id
}

output "confluent_bootstrap_endpoint" {
  description = "Kafka bootstrap endpoint"
  value       = module.core.kafka_cluster_bootstrap_endpoint
}

output "schema_registry_url" {
  description = "Schema Registry REST endpoint"
  value       = module.core.schema_registry_rest_endpoint
}

output "s3_bucket_name" {
  description = "S3 bucket for Tableflow BYOB data"
  value       = aws_s3_bucket.tableflow.bucket
}

output "iam_role_arn" {
  description = "IAM role ARN for Confluent Tableflow"
  value       = aws_iam_role.tableflow.arn
}

output "flink_api_key" {
  description = "Flink API key ID"
  value       = module.core.flink_api_key_id
}

output "flink_api_secret" {
  description = "Flink API key secret"
  value       = module.core.flink_api_key_secret
  sensitive   = true
}

output "demo_env_file" {
  description = "Suggested .env contents for LineageBridge"
  value       = <<-EOT
    # LineageBridge Glue Demo — generated by terraform
    LINEAGE_BRIDGE_CONFLUENT_CLOUD_API_KEY=${var.confluent_cloud_api_key}
    LINEAGE_BRIDGE_CONFLUENT_CLOUD_API_SECRET=${var.confluent_cloud_api_secret}
    LINEAGE_BRIDGE_CLUSTER_CREDENTIALS={"${module.core.kafka_cluster_id}":{"api_key":"${module.core.kafka_api_key_id}","api_secret":"${module.core.kafka_api_key_secret}"}}
    LINEAGE_BRIDGE_SCHEMA_REGISTRY_ENDPOINT=${module.core.schema_registry_rest_endpoint}
    LINEAGE_BRIDGE_SCHEMA_REGISTRY_API_KEY=${module.core.schema_registry_api_key_id}
    LINEAGE_BRIDGE_SCHEMA_REGISTRY_API_SECRET=${module.core.schema_registry_api_key_secret}
    LINEAGE_BRIDGE_TABLEFLOW_API_KEY=${var.confluent_tableflow_api_key}
    LINEAGE_BRIDGE_TABLEFLOW_API_SECRET=${var.confluent_tableflow_api_secret}
    LINEAGE_BRIDGE_FLINK_API_KEY=${module.core.flink_api_key_id}
    LINEAGE_BRIDGE_FLINK_API_SECRET=${module.core.flink_api_key_secret}
    LINEAGE_BRIDGE_AWS_REGION=${var.aws_region}
  EOT
  sensitive   = true
}
