# ── LineageBridge Demo — Outputs ──────────────────────────────────────────────

output "confluent_environment_id" {
  description = "Confluent environment ID — use with lineage-bridge-extract --env"
  value       = confluent_environment.demo.id
}

output "confluent_cluster_id" {
  description = "Confluent Kafka cluster ID"
  value       = confluent_kafka_cluster.demo.id
}

output "confluent_bootstrap_endpoint" {
  description = "Kafka bootstrap endpoint"
  value       = confluent_kafka_cluster.demo.bootstrap_endpoint
}

output "schema_registry_url" {
  description = "Schema Registry REST endpoint"
  value       = data.confluent_schema_registry_cluster.demo.rest_endpoint
}

output "databricks_catalog_name" {
  description = "Databricks Unity Catalog name"
  value       = databricks_catalog.demo.name
}

output "s3_bucket_name" {
  description = "S3 bucket for Tableflow BYOB data"
  value       = aws_s3_bucket.tableflow.bucket
}

output "iam_role_arn" {
  description = "IAM role ARN shared by Confluent Tableflow and Databricks"
  value       = aws_iam_role.tableflow.arn
}

output "demo_env_file" {
  description = "Suggested .env contents for LineageBridge"
  value       = <<-EOT
    # LineageBridge Demo — generated by terraform
    LINEAGE_BRIDGE_CLOUD_API_KEY=${var.confluent_cloud_api_key}
    LINEAGE_BRIDGE_CLOUD_API_SECRET=${var.confluent_cloud_api_secret}
    LINEAGE_BRIDGE_ENVIRONMENT_ID=${confluent_environment.demo.id}
    LINEAGE_BRIDGE_KAFKA_API_KEY=${confluent_api_key.kafka.id}
    LINEAGE_BRIDGE_KAFKA_API_SECRET=${confluent_api_key.kafka.secret}
    LINEAGE_BRIDGE_SCHEMA_REGISTRY_API_KEY=${confluent_api_key.schema_registry.id}
    LINEAGE_BRIDGE_SCHEMA_REGISTRY_API_SECRET=${confluent_api_key.schema_registry.secret}
    LINEAGE_BRIDGE_DATABRICKS_WORKSPACE_URL=${var.databricks_workspace_url}
    LINEAGE_BRIDGE_DATABRICKS_TOKEN=${var.databricks_token}
  EOT
  sensitive   = true
}
