# ── LineageBridge Demo — Outputs ──────────────────────────────────────────────

output "confluent_environment_id" {
  description = "Confluent environment ID — use with lineage-bridge-extract --env"
  value       = confluent_environment.demo.id
}

output "confluent_cluster_id" {
  description = "Confluent Kafka cluster ID"
  value       = confluent_kafka_cluster.demo.id
}

output "confluent_bootstrap_endpoint" {
  description = "Kafka bootstrap endpoint"
  value       = confluent_kafka_cluster.demo.bootstrap_endpoint
}

output "schema_registry_url" {
  description = "Schema Registry REST endpoint"
  value       = data.confluent_schema_registry_cluster.demo.rest_endpoint
}

output "databricks_catalog_name" {
  description = "Databricks Unity Catalog name"
  value       = databricks_catalog.demo.name
}

output "s3_bucket_name" {
  description = "S3 bucket for Tableflow BYOB data"
  value       = aws_s3_bucket.tableflow.bucket
}

output "iam_role_arn" {
  description = "IAM role ARN shared by Confluent Tableflow and Databricks"
  value       = aws_iam_role.tableflow.arn
}

output "postgres_host" {
  description = "PostgreSQL RDS endpoint"
  value       = aws_db_instance.postgres.address
}

output "postgres_password" {
  description = "PostgreSQL password"
  value       = random_password.postgres.result
  sensitive   = true
}

output "flink_api_key" {
  description = "Flink API key ID"
  value       = confluent_api_key.flink.id
}

output "flink_api_secret" {
  description = "Flink API key secret"
  value       = confluent_api_key.flink.secret
  sensitive   = true
}

output "ksqldb_cluster_id" {
  description = "ksqlDB cluster ID"
  value       = confluent_ksql_cluster.demo.id
}

output "ksqldb_endpoint" {
  description = "ksqlDB REST endpoint"
  value       = confluent_ksql_cluster.demo.rest_endpoint
}

output "ksqldb_api_key" {
  description = "ksqlDB API key ID"
  value       = confluent_api_key.ksqldb.id
}

output "ksqldb_api_secret" {
  description = "ksqlDB API key secret"
  value       = confluent_api_key.ksqldb.secret
  sensitive   = true
}

output "bigquery_connector_id" {
  description = "BigQuery sink connector ID (disabled — requires GCP-hosted cluster)"
  value       = ""
}

output "demo_env_file" {
  description = "Suggested .env contents for LineageBridge"
  value       = <<-EOT
    # LineageBridge Demo — generated by terraform
    LINEAGE_BRIDGE_CONFLUENT_CLOUD_API_KEY=${var.confluent_cloud_api_key}
    LINEAGE_BRIDGE_CONFLUENT_CLOUD_API_SECRET=${var.confluent_cloud_api_secret}
    LINEAGE_BRIDGE_CLUSTER_CREDENTIALS={"${confluent_kafka_cluster.demo.id}":{"api_key":"${confluent_api_key.kafka.id}","api_secret":"${confluent_api_key.kafka.secret}"}}
    LINEAGE_BRIDGE_SCHEMA_REGISTRY_ENDPOINT=${data.confluent_schema_registry_cluster.demo.rest_endpoint}
    LINEAGE_BRIDGE_SCHEMA_REGISTRY_API_KEY=${confluent_api_key.schema_registry.id}
    LINEAGE_BRIDGE_SCHEMA_REGISTRY_API_SECRET=${confluent_api_key.schema_registry.secret}
    LINEAGE_BRIDGE_TABLEFLOW_API_KEY=${var.confluent_tableflow_api_key}
    LINEAGE_BRIDGE_TABLEFLOW_API_SECRET=${var.confluent_tableflow_api_secret}
    LINEAGE_BRIDGE_FLINK_API_KEY=${confluent_api_key.flink.id}
    LINEAGE_BRIDGE_FLINK_API_SECRET=${confluent_api_key.flink.secret}
    LINEAGE_BRIDGE_KSQLDB_API_KEY=${confluent_api_key.ksqldb.id}
    LINEAGE_BRIDGE_KSQLDB_API_SECRET=${confluent_api_key.ksqldb.secret}
    LINEAGE_BRIDGE_DATABRICKS_WORKSPACE_URL=${var.databricks_workspace_url}
    LINEAGE_BRIDGE_DATABRICKS_TOKEN=${var.databricks_token}
    LINEAGE_BRIDGE_AWS_REGION=${var.aws_region}
  EOT
  sensitive   = true
}
