# ── Confluent Core Module — Input Variables ─────────────────────────────────

variable "demo_label" {
  description = "Short label identifying the demo variant (e.g. uc, glue, bq)"
  type        = string
  default     = ""
}

variable "demo_suffix" {
  description = <<-EOT
    Optional override for the random suffix appended to ``demo_prefix``.
    When empty (default), an 8-char hex value is generated by ``random_id``.
    Set this from setup-tfvars.sh when bash needs to know the suffix before
    terraform apply (e.g. to ``bq mk`` a BigQuery dataset whose name has to
    match what the connector will write to).
  EOT
  type        = string
  default     = ""

  validation {
    condition     = var.demo_suffix == "" || can(regex("^[a-f0-9]{4,16}$", var.demo_suffix))
    error_message = "demo_suffix must be 4-16 lowercase hex chars (or empty)."
  }
}

variable "cloud_provider" {
  description = "Cloud provider for Kafka cluster and Flink: AWS or GCP"
  type        = string
  default     = "AWS"

  validation {
    condition     = contains(["AWS", "GCP"], var.cloud_provider)
    error_message = "cloud_provider must be AWS or GCP"
  }
}

variable "cloud_region" {
  description = "Cloud region (e.g. us-east-1 for AWS, us-east1 for GCP)"
  type        = string
}

variable "topic_prefix" {
  description = "Prefix for Kafka topic names"
  type        = string
  default     = "lineage_bridge"
}

variable "flink_max_cfu" {
  description = "Maximum CFU for Flink compute pool"
  type        = number
  default     = 5
}
